version: '3.8'

volumes:
  postgres_data: {}

services:
  api:
    depends_on:
      - postgres
    build:
      target: dev
      context: ./
      dockerfile: ./compose/api/Dockerfile
    image: api
    volumes:
      - ./services/api:/app
    ports:
        - "8000:8000"
    env_file:
      - envs/api/.env.dev
  postgres:
    image: postgres:16
    env_file:
      - envs/postgres/.env.dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db}